### ISSUE TITLE
proj will not compile using Microsoft Compiler for Python 2.7

### ISSUE THREAD

**Issue by PaulPorthouse** [OSGeo/PROJ#341]
It appears that the Microsoft Compiler for Python 2.7 
doesn't like the warning pragma and raises a fatal error while compiling when trying to install using pip.

```
C:\Users\ishare\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc -IC:\Python27\include -IC:\Python27\PC /Tcsrc\pj_strtod.c /Fobuild\temp.win32-2.7\Release\src\pj_strtod.obj
pj_strtod.c
src\pj_strtod.c(79) : fatal error C1021: invalid preprocessor command 'warning'
error: command 'C:\\Users\\ishare\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

I have locally commented out the [offending line](https://github.com/OSGeo/proj.4/blob/master/src/pj_strtod.c#L79), and then successfully installed it using pip.

[FailedInstallLog.txt](https://github.com/OSGeo/proj.4/files/80038/FailedInstallLog.txt)

(Note, originally raised it at [PyProj](https://github.com/jswhit/pyproj/issues/42) but was advised to raise it here)

**Comment by rouault** [comment]
Can you make a pull request for that thanks ?

**Comment by micahcochran** [comment]
@PaulPorthouse I found out that I have the same issue.  I've got a patch if you want me to submit a pull request.

**Comment by PaulPorthouse** [comment]
@micahcochran Please, by all means.
